import 'package:rettiwt/model/feeds_model.dart';

class DummyData {
  List<FeedsModel> _dummy = [
    FeedsModel(
      id: 1,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/man.JPG',
      feedcontent: 'feedcontent fsdndjndjv  fjkfndjbjfdsjf djbsjbkfdkjvbdsjvjvdjvbd jdskfhdvhdoivdvd vndjsnvkvdvkdfv sfndnjdfvnjnvjvf dv djvbjdgfdvnfkjv v fkjvnjkfdnvf dkvdfkjvfvjfvfdjbv fdkvfjvfjvbfjkv vfdjjvnfkvnfn fvfdjkvbkjf',
    ),
    FeedsModel(
      id: 2,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/01.jpeg',
      feedcontent: 'feedcontent dcdf d',
    ),
    FeedsModel(id: 3,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/08.jpeg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 4,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/03.jpeg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 5,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/09.jpeg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 6,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/04.jpeg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 7,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/05.jpeg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 8,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/06.jpeg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 9,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/06.jpeg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 10,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/07.jpeg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 11,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/12.jpg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 12,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/19.jpg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 13,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/13.jpg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 14,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/14.jpg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 15,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/15.jpg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 16,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/16.jpg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 17,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/17.jpg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 18,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/18.jpg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 19,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'assets/images/19.jpg',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 20,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 21,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 22,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 23,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 24,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 25,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 26,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 27,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 28,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 29,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 30,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 31,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 32,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 33,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 34,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 35,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 36,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 37,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 38,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 39,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 40,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 41,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 42,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 43,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 44,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 45,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 46,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 47,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 48,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 49,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 50,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(id: 51,
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
  ];

  List<FeedsModel> get dummy => _dummy;
}
