import 'package:rettiwt/model/feeds_model.dart';

class DummyData {
  List<FeedsModel> _dummy = [
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      // imageurl:  Image.asset(
      //     'assets/images/man.JPG',
      //     fit: BoxFit.cover,
      //     scale: 7.0,
      //   ),
      feedcontent: 'feedcontent fsdndjndjv  fjkfndjbjfdsjf djbsjbkfdkjvbdsjvjvdjvbd jdskfhdvhdoivdvd vndjsnvkvdvkdfv sfndnjdfvnjnvjvf dv djvbjdgfdvnfkjv v fkjvnjkfdnvf dkvdfkjvfvjfvfdjbv fdkvfjvfjvbfjkv vfdjjvnfkvnfn fvfdjkvbkjf',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
    FeedsModel(
      username: 'username',
      firstname: 'firstname',
      imageurl: 'imageurl',
      feedcontent: 'feedcontent',
    ),
  ];

  List<FeedsModel> get dummy => _dummy;
}
